// AUTO-GENERATED by tools/process-textures.mjs — do not edit by hand.

/** File-based environment textures available under /assets/textures/. */
export const TEXTURE_MANIFEST: Record<string, { emissive: boolean }> = {
  "wall_concrete": { emissive: false },
  "wall_neon_blue": { emissive: true },
  "wall_neon_pink": { emissive: true },
  "wall_neon_green": { emissive: true },
  "wall_neon_orange": { emissive: true },
  "door_metal": { emissive: true },
  "floor_concrete_wet": { emissive: false },
  "floor_metal_grate": { emissive: false },
  "ceiling_pipes": { emissive: true },
  "ceiling_industrial": { emissive: true },
};
